version: 2

defaults: &defaults
  docker:
    - image: grafana/jsonnet-build:3989b8d

workflows:
  version: 2
  default:
    jobs:
    - lint

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint
