version: 2

defaults: &defaults
  docker:
    - image: docker.io/grafana/jsonnet-build:4fd8fef

workflows:
  version: 2
  default:
    jobs:
    - lint

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint
